Final Submission/cvwo2/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/new' => 'tasks#new'
  get '/home' => 'tasks#index'
  get '/tasks/:id' => 'tasks#show'
  get ':tag' => 'tasks#index'
  get '/' => 'sessions#destroy'

  resources :users
  resources :tasks

end

Final Submission/cvwo2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Final Submission/cvwo2/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
end

Final Submission/cvwo2/app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
    
    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.name = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
      end
end

Final Submission/cvwo2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

Final Submission/cvwo2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to home_path
    
  end

  def destroy
    session.clear
    redirect_to root
  end
  
  private
  def auth
    request.env['omniauth.auth']
  end
end

Final Submission/cvwo2/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        if params[:tag]
          @tasks = current_user.tasks.where("tag like ?", "%#{params[:tag]}%")
        else
          @tasks = current_user.tasks.all
        end
    end

    def show
        @task = current_user.tasks.find(params[:id])
    end
    
    def new
        @task = Task.new
    end
    
    def create
        @task = current_user.tasks.new(task_params)
    
      if @task.save
        redirect_to @task
      else
        render :new
      end
    end

    def edit
      @task = Task.find(params[:id])
    end
  
    def update
      @task = Task.find(params[:id])
  
      if @task.update(task_params)
        redirect_to @task
      else
        render :edit
      end
    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy
  
      redirect_to home_path
    end
    
    private
      def task_params
        params.require(:task).permit(:title, :body, :tag)
      end    
end

Final Submission/cvwo2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
  
    def show
      @tasks = Task.all
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end  
end

Final Submission/cvwo2/app/helpers/application_helper.rb
module ApplicationHelper
end

Final Submission/cvwo2/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
      end
    
      def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    
      def logged_in?
        !current_user.nil?
      end
    
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
end

Final Submission/cvwo2/app/helpers/tasks_helper.rb
module TasksHelper
end

Final Submission/cvwo2/app/helpers/users_helper.rb
module UsersHelper
end

Final Submission/cvwo2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= favicon_link_tag asset_path('task.png') %>
  <head>
    <title>Taskify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-light" style="background-color: #c2f25c;">
  <div class="container-fluid">
    <a class="navbar-brand" href='/home'>
      <img src='http://localhost:3000/packs/media/images/task-0d8f88d6.png' style="width:28px;height:31px;" class="d-inline-block align-top">
      Taskify
    </a>
    <a href='/' class="btn btn-dark" type="submit">Logout</a>
  </div>
</nav>
    <%= yield %>
  </body>
</html>
<%= javascript_pack_tag 'index' %>

Final Submission/cvwo2/app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
    
<ul>
    <div class="mb-3">
    <label for="task_title" class="form-label">Title</label>
    <input type="text" class="form-control" name="task[title]" id="task_title" value=<%= task.title%>>
    </div>
  

    <div class="mb-3">
    <label for="task_body" class="form-label">Details</label>
    <textarea name="task[body]" id="task_body" class="form-control" rows="3"><%= task.body%></textarea>
    </div>

    <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Tag</label>
    <input type="text" class="form-control" id="task_tag" name="task[tag]" value=<%= task.tag%> >
    </div>
  
    <div>
    <button type="submit" class="bbtn btn-outline-primary"><%= form.submit %></button>
    </div>
</ul>
    
  <% end %>

Final Submission/cvwo2/app/views/tasks/edit.html.erb
<ul><h2>Edit Task</h2></ul>

<%= render "form", task: @task %>

Final Submission/cvwo2/app/views/tasks/index.html.erb
<ul>
<h2>Hi <%= @current_user.name%>! </h2>
<h3> Tasks </h3>

<a class="btn btn-warning" href='/new' role="button">Add Task</a>
</ul>
<ul>
  <% @tasks.each do |task| %>       
    <div class="card">
    <h5 class="card-header"><%= task.title %></h5>
    <div class="card-body">
      <h5 class="card-title"><%= task.body%></h5>
      <% if (task.tag).match(/priority/i) %>
      <a href='/<%= task.tag%>' type="button" class="btn btn-outline-danger"><%= task.tag%></a>
      <% elsif (task.tag).match(/low/i)%>
      <a href='/<%= task.tag%>' type="button" class="btn btn-outline-success"><%= task.tag%></a>
      <% else %>
      <a href='/<%= task.tag%>' type="button" class="btn btn-outline-primary"><%= task.tag%></a>
      <% end %>
      <a href=<%= task_path(task)%> class="btn btn-primary">Go to =></a>
    </div>
  </div>  
  <% end %>
</ul>

Final Submission/cvwo2/app/views/tasks/new.html.erb
<ul><h2>New Task</h2></ul>

<%= render "form", task: @task %>

Final Submission/cvwo2/app/views/tasks/show.html.erb
<ul>
</ul>

<div class="card text-center">
  <div class="card-header">
  <%= @task.title %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @task.body %></p></h5>
    <a href=<%= edit_task_path(@task)%> class="btn btn-outline-secondary">Edit</a>
    <a data-confirm="Sure?" data-method="delete" href=<%= task_path(@task)%> class="btn btn-outline-danger">Delete</a>
  </div>
  <div class="card-footer text-muted">
    <%= @task.tag %>
  </div>
</div>